### ISSUE TITLE
next-use-posthog throws error when trying to build after upgrading posthog-js to 1.16.0

### ISSUE THREAD

**Issue by alveshelio** [Ismaaa/next-use-posthog#2]
After upgrading toposthog-js to 1.16.0, next-use-posthog started throwing the error bellow and fails to build, thus deploying on Vercel. 
```
Argument of type 'typeof import("/node_modules/next-use-posthog/node_modules/posthog-js/dist/module").default' is not assignable to parameter of type 'typeof import("/node_modules/posthog-js/dist/module").default'.
  Property 'group' is missing in type 'typeof import("/node_modules/next-use-posthog/node_modules/posthog-js/dist/module").default' but required in type 'typeof import("/node_modules/posthog-js/dist/module").default'.

 opt_out_capturing_by_default: true,
 loaded: (client) => {
       analytics.init(client)
                            ^
       askUserConsent()
     },
   })
```

Adding `any` like so `analytics.init(client as any)` fixes the issue and it builds. Could this be because next-use-posthog needs to upgrade posthog to latest version?.

**Comment by Ismaaa** [comment]
You can now use the version `1.16.0` which comes with `posthog-js@1.16.0` 👍

**Comment by alveshelio** [comment]
> You can now use the version `1.16.0` which comes with `posthog-js@1.16.0` 👍

I'm not sure what you mean. Does it means that I don't need next-use-posthog anymore? Does posthog-js has this hook?

**Comment by alveshelio** [comment]
Indeed, it does solve the problem. So does it means also that I don't need to install posthog-js since it's already included in next-use-posthog?

Thank you

**Comment by Ismaaa** [comment]
That's correct @alveshelio :)
