### ISSUE TITLE
BUG: After nextjs upgrade usePosthog hook breaks router 

### ISSUE THREAD

**Issue by sanderkooger** [Ismaaa/next-use-posthog#9]
After we upgraded nextjs in our app posthog has issues with an unmounted Next.router

NextJS version :  "next": "^13.1.2",
usePosthog version:    "next-use-posthog": "^1.16.4",

'''
export default function App({ Component, pageProps }: AppProps) {
  const isLoggedIn = useReactiveVar(isLoggedInVAR);
  const isClientSide = typeof window !== 'undefined';

  const apolloClient = useApollo(pageProps);
  const router = useRouter();

  // TODO: Find out why posthog breaks router
  console.log(process.env.NEXT_PUBLIC_POSTHOG_API_KEY, process.env.NEXT_PUBLIC_POSTHOG_API_HOST);
  usePostHog(process.env.NEXT_PUBLIC_POSTHOG_API_KEY || '', {
    api_host: process.env.NEXT_PUBLIC_POSTHOG_API_HOST || '',
    loaded: (posthog) => {
      if (process.env.NEXT_PUBLIC_POSTHOG_ENABLED === 'false') posthog.opt_out_capturing();
    }
  });
'''

The error we get is 

Server Error
Error: Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
Object.useRouter
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/next@13.1.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/router.js (122:15)
usePostHog
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/next-use-posthog@1.16.4_react@18.2.0/node_modules/next-use-posthog/dist/index.js (11:29)
src/pages/_app.tsx (47:13) @ process

  45 | // TODO: Find out why posthog breaks router
  46 | console.log(process.env.NEXT_PUBLIC_POSTHOG_API_KEY, process.env.NEXT_PUBLIC_POSTHOG_API_HOST);
> 47 | usePostHog(process.env.NEXT_PUBLIC_POSTHOG_API_KEY || '', {
     |           ^
  48 |   api_host: process.env.NEXT_PUBLIC_POSTHOG_API_HOST || '',
  49 |   loaded: (posthog) => {
  50 |     if (process.env.NEXT_PUBLIC_POSTHOG_ENABLED === 'false') posthog.opt_out_capturing();
Call Stack
renderWithHooks
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5658:16)
renderIndeterminateComponent
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5731:15)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderIndeterminateComponent
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5785:7)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5971:9)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5971:9)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderContextProvider
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5920:3)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6017:11)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderContextProvider
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5920:3)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6017:11)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderIndeterminateComponent
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5785:7)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderContextProvider
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5920:3)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6017:11)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderContextProvider
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5920:3)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6017:11)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderContextProvider
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5920:3)
renderElement
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6017:11)
renderNodeDestructiveImpl
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/sander/code/TIF-Monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)

The app runs if we quaote out useposthog. 

Please advice

**Comment by Ismaaa** [comment]
Hi @sanderkooger !
Please, feel free to open an issue [here](https://github.com/PostHog/posthog-nextjs)
